/*
    AUTO-GENERATED MANIFOLDC INTERNAL WRAPPER FUNCTIONS
    This file is automatically generated by gen_csharp.py
    DO NOT EDIT MANUALLY

    WebAssembly/Emscripten cannot marshal structs returned by value through P/Invoke.
    These _internal helper functions work around this limitation by taking an output
    pointer parameter instead.
*/

#ifndef MANIFOLDC_CSHARP_INTERNAL_WRAPPERS_H
#define MANIFOLDC_CSHARP_INTERNAL_WRAPPERS_H

#include <manifold/manifoldc.h>
#include <manifold/types.h>

// For Emscripten builds, these functions need to be exported
#ifdef __EMSCRIPTEN__
    #include <emscripten.h>
    #define MANIFOLDC_EXPORT EMSCRIPTEN_KEEPALIVE
#else
    #define MANIFOLDC_EXPORT
#endif

// ========== Manifoldc (manifold_) ===========

MANIFOLDC_EXPORT void manifold_simple_polygon_get_point_internal(ManifoldVec2* result, ManifoldSimplePolygon * p, size_t idx) {
    *result = manifold_simple_polygon_get_point(p, idx);
}

MANIFOLDC_EXPORT void manifold_polygons_get_point_internal(ManifoldVec2* result, ManifoldPolygons * ps, size_t simple_idx, size_t pt_idx) {
    *result = manifold_polygons_get_point(ps, simple_idx, pt_idx);
}

MANIFOLDC_EXPORT void manifold_split_internal(ManifoldManifoldPair* result, void * mem_first, void * mem_second, ManifoldManifold * a, ManifoldManifold * b) {
    *result = manifold_split(mem_first, mem_second, a, b);
}

MANIFOLDC_EXPORT void manifold_split_by_plane_internal(ManifoldManifoldPair* result, void * mem_first, void * mem_second, ManifoldManifold * m, double normal_x, double normal_y, double normal_z, double offset) {
    *result = manifold_split_by_plane(mem_first, mem_second, m, normal_x, normal_y, normal_z, offset);
}

MANIFOLDC_EXPORT void manifold_rect_min_internal(ManifoldVec2* result, ManifoldRect * r) {
    *result = manifold_rect_min(r);
}

MANIFOLDC_EXPORT void manifold_rect_max_internal(ManifoldVec2* result, ManifoldRect * r) {
    *result = manifold_rect_max(r);
}

MANIFOLDC_EXPORT void manifold_rect_dimensions_internal(ManifoldVec2* result, ManifoldRect * r) {
    *result = manifold_rect_dimensions(r);
}

MANIFOLDC_EXPORT void manifold_rect_center_internal(ManifoldVec2* result, ManifoldRect * r) {
    *result = manifold_rect_center(r);
}

MANIFOLDC_EXPORT void manifold_box_min_internal(ManifoldVec3* result, ManifoldBox * b) {
    *result = manifold_box_min(b);
}

MANIFOLDC_EXPORT void manifold_box_max_internal(ManifoldVec3* result, ManifoldBox * b) {
    *result = manifold_box_max(b);
}

MANIFOLDC_EXPORT void manifold_box_dimensions_internal(ManifoldVec3* result, ManifoldBox * b) {
    *result = manifold_box_dimensions(b);
}

MANIFOLDC_EXPORT void manifold_box_center_internal(ManifoldVec3* result, ManifoldBox * b) {
    *result = manifold_box_center(b);
}

#endif // MANIFOLDC_CSHARP_INTERNAL_WRAPPERS_H
